// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  formsSidebar: [{ type: "autogenerated", dirName: "forms" }],
};

module.exports = sidebars;
