name: Build and push Docker image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push the Docker image
        run: |
          docker build . -f Dockerfile -t ghcr.io/bitwarden/test-the-web:latest
          docker push ghcr.io/bitwarden/test-the-web:latest
